spring:
  application:
    name: core-data-management-ms

  data:
    mongodb:
#      port: 27017
#      host: localhost
      database: octopus
      uri: mongodb+srv://octohealth:future@cluster0.svyi6.mongodb.net/octopus?retryWrites=true&w=majority

server:
  servlet:
    context-path: /coreDataManagement/v1
  http2:
    enabled: true
  port: 9000
